name: Chromatic CI

on:
  push:

jobs:
  chromatic-ci:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # needed by chromatic for git history

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: PNPM cache via actions/cache@v3
        id: pnpm-cache
        uses: actions/cache@v3
        with:
          path: /home/runner/work/design-system/design-system/common/temp/pnpm-store/v3
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install dependencies
        run: node common/scripts/install-run-rush.js install

      - name: Build components
        run: node common/scripts/install-run-rush.js build --timeline

      - name: Build Storybook
        working-directory: ./
        env:
          CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
        run: node common/scripts/install-run-rush.js build:storybook
