name: Rush Design System CI

on:
  push:
  workflow_dispatch:

jobs:
  design-system-ci:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache Rush
        uses: actions/cache@v4
        with:
          path: |
            common/temp/install-run
            ~/.rush
          key: ${{ runner.os }}-rush-${{ hashFiles('rush.json') }}

      - name: Cache PNPM
        uses: actions/cache@v4
        with:
          path: common/temp/pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-pnpm-

      - name: Install dependencies
        run: node common/scripts/install-run-rush.js install

      - name: rush change --verify
        run: node common/scripts/install-run-rush.js change --verify

      - name: Build components
        run: node common/scripts/install-run-rush.js build --timeline

      - name: Run Unit Tests
        run: node common/scripts/install-run-rush.js test:ci

      - name: ESLint
        run: node common/scripts/install-run-rush.js lint

      - name: Generate and upload coverage report
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          npx codecov
