name: Rush Design System CI

on:
  push:
    branches:
      - '*'

jobs:
  design-system-ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: PNPM cache via actions/cache@v2
        id: pnpm-cache
        uses: actions/cache@v2
        with:
          path: /home/runner/work/design-system/design-system/common/temp/pnpm-store/v3
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install dependencies
        run: node common/scripts/install-run-rush.js install

      - name: Build components
        run: node common/scripts/install-run-rush.js build

      - name: Build Storybook
        if: ${{ matrix.node-version == '12.x' }}
        working-directory: ./
        env:
          CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
        run: node common/scripts/install-run-rush.js build:storybook

      - name: Run Unit Tests
        run: node common/scripts/install-run-rush.js test:ci

      - name: ESLint
        run: node common/scripts/install-run-rush.js lint

      - name: Generate and upload coverage report
        if: ${{ matrix.node-version == '10.x' }}
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          npx codecov
