# This workflow is to create a baseline for comparison in PRs via Chromatic
# It is necessary due to our `Squash and merge` strategy, where the head commit changes and
# Chromatic doesn't have a proper ref to compare changes to.
# See https://www.chromatic.com/docs/ci#github-squash-rebase-merge-and-the-master-branch for more information

name: Storybook Baseline for Chromatic
on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          fetch-depth: 0

      - name: PNPM cache via actions/cache@v2
        id: pnpm-cache
        uses: actions/cache@v2
        with:
          path: /home/runner/work/design-system/design-system/common/temp/pnpm-store/v3
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install dependencies
        run: node common/scripts/install-run-rush.js install

      - name: Build components
        run: node common/scripts/install-run-rush.js build

      - name: Build Storybook
        working-directory: ./
        env:
          CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
        run: node common/scripts/install-run-rush.js build:storybook:baseline
