name: Rush publish to apply changes

on: workflow_dispatch

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  create-release:
    # Name the Job
    name: Rush publish apply
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      - name: PNPM cache via actions/cache@v2
        id: pnpm-cache
        uses: actions/cache@v2
        with:
          path: /home/runner/work/design-system/design-system/common/temp/pnpm-store/v3
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install dependencies
        run: node common/scripts/install-run-rush.js install

      - name: Build components
        run: node common/scripts/install-run-rush.js build

      - name: Apply changes
        run: |
          node common/scripts/install-run-rush.js publish --apply --add-commit-details

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: 'Rush publish apply'
          commit-message: 'Run rush publish apply to create a new release'
          branch: apply-changes
          delete-branch: true
          branch-suffix: 'timestamp'
